#!/bin/bash

   USUARIO="root"
if [ -z "$MYSQL_ENV_MYSQL_DATABASE" ]
then 
    DATABASE="wordpress"
else
	DATABASE= $MYSQL_ENV_MYSQL_DATABASE
fi

if [ -z "$MYSQL_ENV_MYSQL_ROOT_PASSWORD" ]; then echo "Error: MYSQL_ENV_MYSQL_ROOT_PASSWORD not set"; echo "Finished: FAILURE"; exit 1; fi


echo 'creating database dump'
mysqldump -h mysql --add-drop-table -u$root -p $MYSQL_ENV_MYSQL_DATABASE --password=$MYSQL_ENV_MYSQL_ROOT_PASSWORD | bzip2 -c > /backups/backup_`date '+%Y%m%d'`.sql.bz2

echo 'Finished: SUCCESS'
