#!/bin/bash
 
   USUARIO="root"
if [ -z "$MYSQL_ENV_MYSQL_DATABASE" ]
then 
    DATABASE="wordpress"
else
	DATABASE= $MYSQL_ENV_MYSQL_DATABASE
fi

if [ -z "$MYSQL_ENV_MYSQL_ROOT_PASSWORD" ]; then echo "Error: MYSQL_ENV_MYSQL_ROOT_PASSWORD not set"; echo "Finished: FAILURE"; exit 1; fi
if [ -z "$MYSQL_PORT_3306_TCP_PORT" ]; then echo "Error: MYSQL_PORT_3306_TCP_PORT not set"; echo "Finished: FAILURE"; exit 1; fi


if ! [[ $1 ]]
then
  NOMBRE=$(ls /backups|cut -c 8-15|sort -n|tail -1)
else
  NOMBRE=$1
fi


if ! [[ $NOMBRE =~ ^[a-zA-Z0-9_-]+$ ]]
then
  echo "The given backup name does not match the expected pattern: only characters, digits, underscore and dash are allowed ([a-zA-Z0-9_-])."
  echo 'Finished: FAILURE'
  exit 1
fi

SQL_ARCHIVE="/backups/backup_$NOMBRE.sql.bz2"


if [[ ! -f $SQL_ARCHIVE ]]
then
  echo "The file $SQL_ARCHIVE does not exist. Aborting."
  echo "Finished: FAILURE."
  exit 1
fi

# restore database
echo "restoring data from mysql dump file $SQL_ARCHIVE"
bunzip2 < $SQL_ARCHIVE | mysql -u$USUARIO -p $DATABASE -p$MYSQL_ENV_MYSQL_ROOT_PASSWORD -h mysql 

echo 'Finished: SUCCESS'
